fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace

- repo: https://github.com/hcodes/yaspeller.git
  rev: v8.0.1
  hooks:
    - id: yaspeller
      files: "\\.en"
